In [1]:
import numpy as np

In [2]:
a = [1,2,3]

In [3]:
type(a)

list

In [5]:
b = np.array(a)

In [6]:
type(b)

numpy.ndarray

In [7]:
range(1,10)

range(1, 10)

In [11]:
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
c = [[1,2,3],[10,20,30]],

In [18]:
np.array(c)

array([[[ 1,  2,  3],
        [10, 20, 30]]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
z = np.arange(0,30)

In [31]:
z.shape

(30,)

In [34]:
z.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [35]:
a = [1,2,3]

In [36]:
a[2]

3

In [37]:
np.array(a)

array([1, 2, 3])

In [40]:
ten = np.arange(0,10)

In [47]:
ten[3:5]

array([3, 4])

In [50]:
ten[:6]

array([0, 1, 2, 3, 4, 5])

In [52]:
ten[6:]

array([6, 7, 8, 9])

In [62]:
first_ten = np.arange(10)

In [54]:
first_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
first_ten -10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [58]:
first_ten+first_ten

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
first_ten*first_ten

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [63]:
first_ten[:] = 10

In [64]:
first_ten

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [65]:
first_ten = np.arange(0,10)

In [67]:
first_five = first_ten[:5]

In [68]:
first_five

array([0, 1, 2, 3, 4])

In [69]:
first_five[:] = 0

In [70]:
first_five

array([0, 0, 0, 0, 0])

In [71]:
first_ten

array([0, 0, 0, 0, 0, 5, 6, 7, 8, 9])